name: CI
run-name: CI
on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Compiler Check
        run: |
          echo "Compiler checking TBD"
      - name: Src Vonurability Scan
        run: |
          echo "src vonurability scan TBD"
      - name: Linting
        run: |
          echo "Linting TBD"
      - name: Build
        run: |
          echo "Building TBD"
      - name: Unit Test
        run: |
          echo "Unit testing TBD"
      - name: Integration Test
        run: |
          echo "Integration Testing TBD"
      - name: Binary upload
        run: |
          echo "Binary upload Testing TBD"
      - name: Container build
        run: |
          echo "Continer Build TBD"
      - name: Container Vonurability Scan
        run: |
          echo "Continer build TBD"
      - name: Container Upload
        run: |
          echo "Continer upload TBD"
      - name: Sleeper
        run: sleep 35