name: main-flow-pull-requests
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: 
  pull_request:
    branches:
      - main

jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Put stuff to do when merging to main here! Such things could include deploying"